all:
    children:
        cluster:
            children:
                consul:
                    children:
                        consul-leader:
                            hosts:
                                192.168.2.70:

                        consul-servers:
                            hosts:
                                192.168.2.71:
                                192.168.2.72:

                        consul-clients:
                            hosts:

                nomad:
                    children:
                        nomad-leader:
                            hosts:
                                192.168.2.70:

                        nomad-servers:
                            hosts:
                                192.168.2.71:
                                192.168.2.72:

                        nomad-clients:
                            hosts:

                vault:
                    children:
                        vault-active:
                            hosts:
                                192.168.2.70:

                        vault-standby:
                            hosts:
                                192.168.2.71:
                                192.168.2.72:
