all:
    children:
        cluster:
            children:
                consul:
                    children:
                        consul-leader:
                            hosts:
                                192.168.2.70:
                        consul-servers:
                            hosts:
                                192.168.2.71:
                                192.168.2.72:
                        consul-clients:
                            hosts:
                                192.168.2.80:
                                192.168.2.81:
                                192.168.2.82:
                nomad:
                    children:
                        nomad-leader:
                            hosts:
                                192.168.2.70:
                        nomad-servers:
                            hosts:
                                192.168.2.71:
                                192.168.2.72:
                        nomad-clients:
                            hosts:
                                192.168.2.80:
                                    nomad_client_meta:
                                        species: "genpurpose"
                                        haproxy: "true"
                                192.168.2.81:
                                    nomad_client_meta:
                                        species: "genpurpose"
                                        haproxy: "true"
                                192.168.2.82:
                                    nomad_client_meta:
                                        species: "genpurpose"
                                        haproxy: "true"
                vault:
                    children:
                        vault-active:
                            hosts:
                                192.168.2.70:
                        vault-standby:
                            hosts:
                                192.168.2.71:
                                192.168.2.72:
                                
