- name: Check if vault is initialized.
  uri:
    url: https://{{docker_bridge_gateway}}:8200/v1/sys/init
    method: GET
    client_cert: /vault_config/ssl/vault-cli.pem
    client_key: /vault_config/ssl/vault-cli-key.pem
    validate_certs: no
    return_content: yes
    status_code: 200
    body_format: json
  register: vault_init_status
  until: vault_init_status.status == 200
  retries: 5
  delay: 5

- fail:
    msg: "Variable '{{ item }}' is not defined"
  when: item not in vars
  with_items:
    - vault_init_status

- fail:
    msg: "Variable vault_init_status.initialized is not defined"
  when: vault_init_status.json.initialized is undefined

- fail:
    msg: "Vault is not initialized"
  when: vault_init_status.json.initialized == False

- name: Read unseal keys from unseal_keys.json
  include_vars:
    file: "../../../{{vault_unseal_keys_path}}/unseal_keys.json"
    name: vault_unseal_keys