- fail: 
    msg: "vault_unseal_keys.keys_base64 is undefined"
  when: vault_unseal_keys.keys_base64 is undefined

- fail: 
    msg: "vault_unseal_keys.keys_base64[0] is undefined"
  when: vault_unseal_keys.keys_base64[0] is undefined

- fail: 
    msg: "vault_unseal_keys.keys_base64[1] is undefined"
  when: vault_unseal_keys.keys_base64[1] is undefined

- fail: 
    msg: "vault_unseal_keys.keys_base64[2] is undefined"
  when: vault_unseal_keys.keys_base64[2] is undefined

- fail: 
    msg: "Variable '{{ item }}' is not defined"
  when: item not in vars
  with_items:
    - docker_bridge_bip
    - vault_unseal_keys_path