- name: Install common configuration.
  hosts: cluster
  sudo: yes

  roles:
    - nodes_preconfig
    - nodes_common
    - nodes_postconfig

- name: Install worker configuration.
  hosts: consul-clients

  roles:
     - nodes_worker_config