- fail:
    msg: "Variable '{{ item }}' is not defined"
  when: item not in vars
  with_items:
     - encryption_keys_path

- name: Load acl_data_center_master_token encryption key.
  include_vars:
    file: "../../../{{encryption_keys_path}}/consul/acl_datacenter_master_token.json"