- name: Ensures /fetch_data dir exists
  file:
    path: /fetch_data
    state: directory
    owner: "{{nomad_config_owner}}"
    group: admin
    mode: 0755

- name: Ensures /fetch_data/nomad dir exists
  file:
    path: /fetch_data/nomad
    state: directory
    owner: "{{nomad_config_owner}}"
    group: admin
    mode: 0755

- name: Load the existing consul acl policies
  uri:
    url: "https://consul.service.consul:8501/v1/acl/list"
    method: GET
    client_cert: /consul_config/ssl/consul-cli.pem
    client_key: /consul_config/ssl/consul-cli-key.pem
    validate_certs: no
    status_code: 200
    headers:
      X-Consul-Token: "{{acl_datacenter_master_token}}"
    body_format: json
    return_content: yes
  register: acls

- name: "Set the nomad_acl_name = nomad_{{nomad_acl_type}}_token_{{ansible_hostname}}"
  set_fact:
    nomad_acl_name: nomad_{{nomad_acl_type}}_token_{{ansible_hostname}}

- name: Set the acl fetch path.
  set_fact:
    acl_fetch_path: "../../{{acl_token_path}}/consul/{{ansible_hostname}}_{{nomad_acl_type}}_nomad_acl.json"

- name: Create nomad acl policy
  uri:
    url: "https://consul.service.consul:8501/v1/acl/create"
    method: PUT
    client_cert: /consul_config/ssl/consul-cli.pem
    client_key: /consul_config/ssl/consul-cli-key.pem
    validate_certs: no
    status_code: 200
    headers:
      X-Consul-Token: "{{acl_datacenter_master_token}}"
    body: "{{ lookup('template', 'nomad_acl.json.j2') }}"
    body_format: json
    return_content: yes
    dest: /fetch_data/nomad/nomad_acl.json
  when: nomad_acl_name not in acls.json|map(attribute='Name')|list|unique

- name: Fetch the acl policy for nomad.
  fetch:
    flat: yes
    src: /fetch_data/nomad/nomad_acl.json
    dest: "{{acl_fetch_path}}"
  when: nomad_acl_name not in acls.json|map(attribute='Name')|list|unique

- name: Load the nomad_acl_token ID
  include_vars:
    file: "../../../{{acl_token_path}}/consul/{{ansible_hostname}}_{{nomad_acl_type}}_nomad_acl.json"
    name: nomad_acl_id
  when: nomad_acl_name in acls.json|map(attribute='Name')|list|unique

- name: Update nomad acl policy
  uri:
    url: "https://consul.service.consul:8501/v1/acl/update"
    method: PUT
    client_cert: /consul_config/ssl/consul-cli.pem
    client_key: /consul_config/ssl/consul-cli-key.pem
    validate_certs: no
    status_code: 200
    headers:
      X-Consul-Token: "{{acl_datacenter_master_token}}"
    body: "{{ lookup('template', 'nomad_acl.json.j2') }}"
    body_format: json
    return_content: yes
    dest: /fetch_data/nomad/nomad_acl.json
  when: nomad_acl_name in acls.json|map(attribute='Name')|list|unique

