- name: Set fact external_ip
  set_fact:
    external_ip: "{{ansible_default_ipv4.address}}"

- name: Load acl_data_center_master_token encryption key.
  include_vars:
    file: "../../../{{encryption_keys_path}}/consul/acl_datacenter_master_token.json"