- name: Log into DockerHub
  docker_login:
    username: "{{docker_creds.docker_user_name}}"
    password: "{{docker_creds.docker_user_password}}"
    email: "{{docker_creds.docker_user_email}}"
  become: false
  become_user: wag_ansible_automation
  retries: 5
  delay: 1
  register: result
  until: result|succeeded