- name: Ensures /etc/docker dir exists
  file:
    path: /etc/docker
    state: directory

- template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json

- name: unmask the docker service.
  shell: systemctl unmask docker.service && systemctl unmask docker.socket

- name: Bounce the docker daemon.
  service:
    name: docker
    enabled: yes
    state: restarted