- name: Add a bashrc
  shell: cp /etc/skel/.bashrc ~

- name: Install utility tools
  apt:
    name:  "{{item}}"
    state: present
  with_items:
    - ca-certificates
    - wget
    - curl
    - python-pip
    - git
    - dnsmasq
    - build-essential
    - resolvconf
  retries: 5
  delay: 1
  register: result
  until: result is succeeded

- name: Set low speed timeouts for git
  shell: git config --global http.lowSpeedLimit 500 && git config --global http.lowSpeedTime 60

- name: Uninstall old versions of docker
  apt:
    name: "{{item}}"
    state: absent
  with_items:
    - docker
    - docker-ce

- name: Creates ~/Go/Projects directory
  file:
    path: ~/Go/Projects
    state: directory

- name: Unzip go.
  unarchive:
    remote_src: yes
    src: https://dl.google.com/go/go1.10.2.linux-armv6l.tar.gz
    dest: /usr/local
  retries: 5
  delay: 1
  register: result
  until: result is succeeded

- name: Add GOROOT
  lineinfile:
    path: ~/.bashrc
    regexp: export GOROOT=/usr/local/go
    insertafter: EOF
    line: export GOROOT=/usr/local/go

- name: Add GOPATH
  lineinfile:
    path: ~/.bashrc
    regexp: export GOPATH=$HOME/Go/Projects
    insertafter: EOF
    line: export GOPATH=$HOME/Go/Projects

- name: Update PATH
  lineinfile:
    path: ~/.bashrc
    regexp: export PATH=$GOPATH/bin:$GOROOT/bin:$PATH
    insertafter: EOF
    line: export PATH=$GOPATH/bin:$GOROOT/bin:$PATH

- name: Install Docker dependencies
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - apt-transport-https
    - gnupg2
    - software-properties-common
  retries: 5
  delay: 1
  register: result
  until: result is succeeded

- name: Add docker gpg key
  shell: curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -

- name: Setup docker repo
  shell: echo "deb [arch=armhf] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list && apt-get update

- name: Install Docker
  apt:
    name: docker-ce
    state: present
  retries: 5
  delay: 1
  register: result
  until: result is succeeded

- name: Install docker-py
  pip:
    name: docker-py
    state: latest
    extra_args: --trusted-host pypi.python.org
  retries: 5
  delay: 1
  register: result
  until: result is succeeded

- name: Setup resolvconf base
  lineinfile:
    path: /etc/resolvconf/resolv.conf.d/base
    regexp: nameserver 127.0.0.1
    insertafter: EOF
    line: nameserver 127.0.0.1

- name: Regenerate resolvconf
  shell: resolvconf -u