- name: Creates ~/Go/Projects directory
  file:
    path: ~/Go/Projects
    state: directory

- name: Unzip go.
  unarchive:
    remote_src: yes
    src: https://dl.google.com/go/go1.10.2.linux-armv6l.tar.gz
    dest: /usr/local
  retries: 5
  delay: 1
  register: result
  until: result is succeeded

- name: Add GOROOT
  lineinfile:
    path: ~/.bashrc
    regexp: export GOROOT=/usr/local/go
    insertafter: EOF
    line: export GOROOT=/usr/local/go

- name: Add GOPATH
  lineinfile:
    path: ~/.bashrc
    regexp: export GOPATH=$HOME/Go/Projects
    insertafter: EOF
    line: export GOPATH=$HOME/Go/Projects

- name: Update PATH
  lineinfile:
    path: ~/.bashrc
    regexp: export PATH=$GOPATH/bin:$GOROOT/bin:$PATH
    insertafter: EOF
    line: export PATH=$GOPATH/bin:$GOROOT/bin:$PATH

- name: Install cfssl
  shell: go get -u github.com/cloudflare/cfssl/cmd/...
  environment: "{{go_env}}"
  retries: 5
  delay: 1
  register: result
  until: result is succeeded